# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
script: 
  - |
    travis_wait 30 R CMD build .
    travis_wait 30 R CMD check basket*tar.gz
r_packages:
  - covr
  - testthat
after_success:
  - travis_wait 30 Rscript -e 'covr::codecov()'

