# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
script: 
  - |
    travis_wait 30 R CMD check --no--vignettes basket*tar.gz
r_packages:
  - covr
  - testthat
after_success:
  - Rscript -e 'covr::codecov()'

